spring:
  datasource:
    url: jdbc:oracle:thin:@10.5.7.130:1521:orcl?useUnicode=true&characterEncoding=utf8
    username: EMS
    password: EMS
    driver-class-name: oracle.jdbc.OracleDriver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  typeAliasesPackage: com.longcheng.xxh.energycenter.entity
  mapperLocations: classpath:mapper/*.xml

